# **2. Numpy exercises**

1. Import the numpy package under the name `np`

`hint: import … as`

In [1]:
import numpy as np

2. Create a null vector of size 10

`hint: np.zeros`

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 0 to 100

`hint: arange`

In [4]:
np.arange(0, 101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

4. Create a 10x10 matrix with random values and find the minimum, maximum, and mean values. Normalize the said matrix 

`hint: min, max, ...`

In [8]:
r = np.random.rand(10, 10)
print(r.min())
print(r.max())
print(r.mean())
d = np.linalg.det(r)
print(r / d)

0.001156809685751048
0.9975638365983707
0.4904635311582181
[[ -21.33022849  -41.26286113  -65.81318466   -2.35083006 -174.72346304
   -97.19035529  -36.72753559 -102.57468432 -171.89657628 -158.36592427]
 [-161.59560115  -32.03056702  -85.41781384  -69.65383867 -183.21107331
  -116.15349064  -33.42134458 -101.08931939 -181.89265725 -130.66837123]
 [ -50.78013213 -113.67144726  -21.38013192  -35.45825988 -144.51257447
  -170.39196632  -76.51080761  -35.98056768  -14.77559288 -109.39645982]
 [-144.29672091   -7.30278855 -138.77627795 -176.78492987  -18.08936292
   -22.30214204 -166.47637218  -40.65465513 -163.54549877   -9.79836405]
 [ -53.83770541  -99.14176643 -123.60085656 -122.8181543  -105.46304578
   -75.34397036 -148.80888968  -31.85666633 -155.29805004 -123.89185108]
 [-146.25076642 -126.92158277  -99.25670864 -176.26049829  -73.85142256
  -129.81516354 -103.86570241  -63.66751447  -56.20878573  -62.39866317]
 [-143.12026475  -89.10271186  -41.35703196 -176.50419895  -71.25615307

5. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

`hint: np.sqrt, np.arctan2`

In [15]:
coords = (np.random.rand(10, 2) * 100).astype(int)
dist = np.sqrt(coords[:, 0]**2 + coords[:, 1]**2)
angle = np.arctan2(coords[:, 0], coords[:, 1])
polar = np.vstack((dist, angle)).T
print(polar)

[[ 88.86506625   0.6817707 ]
 [ 93.90420651   1.43191131]
 [ 18.43908891   0.21866895]
 [ 89.55445271   1.15710711]
 [113.35784049   0.72297935]
 [ 26.62705391   0.97237743]
 [123.76186812   0.76825699]
 [ 17.08800749   0.35877067]
 [ 28.01785145   1.53509721]
 [ 86.68333173   0.68735289]]


6. Create random vector of size 10 and replace the maximum value by 0

`hint: argmax`

In [21]:
r = np.random.rand(10)
print(r)
r[r.argmax()] = 0
print(r)

[0.16887113 0.00696898 0.39893057 0.69198289 0.81983921 0.12084679
 0.37248768 0.1470519  0.42262917 0.77044296]
[0.16887113 0.00696898 0.39893057 0.69198289 0.         0.12084679
 0.37248768 0.1470519  0.42262917 0.77044296]


7. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

`hint: np.linspace and np.meshgrid`

In [44]:
sp = np.linspace(0, 5, 6)
b = np.zeros((6, 6), dtype=[('x', int), ('y', int)])
for x in range(6):
    for y in range(6):
        b[x, y] = (sp[x], sp[y])
print(b)

[[(0, 0) (0, 1) (0, 2) (0, 3) (0, 4) (0, 5)]
 [(1, 0) (1, 1) (1, 2) (1, 3) (1, 4) (1, 5)]
 [(2, 0) (2, 1) (2, 2) (2, 3) (2, 4) (2, 5)]
 [(3, 0) (3, 1) (3, 2) (3, 3) (3, 4) (3, 5)]
 [(4, 0) (4, 1) (4, 2) (4, 3) (4, 4) (4, 5)]
 [(5, 0) (5, 1) (5, 2) (5, 3) (5, 4) (5, 5)]]


8. Having a scalar `x` and a random vector `v`, find a value in `v` that is closest to `x`

`hint: argmin`

In [70]:
x = np.random.randint(0, 10)
v = np.random.randint(0, 10, 10)
print(x, v)
print(abs((v - x)).argmin())

7 [2 4 5 0 3 0 7 5 2 4]
6


9. Consider a random vector with shape (100,2) representing coordinates, find point by point distances and put them in a (100,100) array.

In [73]:
r = np.random.randint(0, 100, (100, 2))
nyu = np.zeros((100, 100))
for i in range(100):
    fro = r[i]
    for j in range(100):
        to = r[j]
        dist = np.sqrt((fro[0] - to[0])**2 + (fro[1] - to[1])**2)
        nyu[i, j] = dist

print(nyu)

[[ 0.         56.14267539 33.61547263 ... 45.48626166 29.15475947
  22.8035085 ]
 [56.14267539  0.         34.20526275 ... 46.01086828 83.29465769
  76.15773106]
 [33.61547263 34.20526275  0.         ... 55.14526272 62.60990337
  47.09564736]
 ...
 [45.48626166 46.01086828 55.14526272 ...  0.         58.5918083
  67.47592163]
 [29.15475947 83.29465769 62.60990337 ... 58.5918083   0.
  26.57066051]
 [22.8035085  76.15773106 47.09564736 ... 67.47592163 26.57066051
   0.        ]]


10. Create a random (100, 100) matrix with values from 0 to 1. Turn all values lower than 0.5 into 0.0

In [78]:
r = np.random.rand(100, 100)
r[r < 0.5] = 0
r

array([[0.79081823, 0.7123334 , 0.58335054, ..., 0.70304731, 0.        ,
        0.80240758],
       [0.        , 0.92902934, 0.        , ..., 0.7403303 , 0.5314211 ,
        0.69254807],
       [0.        , 0.        , 0.        , ..., 0.7158282 , 0.        ,
        0.64805717],
       ...,
       [0.        , 0.7360613 , 0.96188442, ..., 0.        , 0.        ,
        0.        ],
       [0.72062082, 0.63227523, 0.61988561, ..., 0.        , 0.6592388 ,
        0.5612404 ],
       [0.        , 0.        , 0.51170647, ..., 0.        , 0.        ,
        0.        ]])

11. Sort an array by the nth column.

In [79]:
n=2
r[r[:, n].argsort()]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.62835654,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.54570232, 0.63300627,
        0.84706279],
       [0.68953673, 0.        , 0.        , ..., 0.77384186, 0.        ,
        0.        ],
       ...,
       [0.81995873, 0.86888028, 0.96873451, ..., 0.98854045, 0.79915597,
        0.85892971],
       [0.50333531, 0.        , 0.9697432 , ..., 0.66529415, 0.        ,
        0.        ],
       [0.        , 0.55292167, 0.99675177, ..., 0.66479604, 0.86740966,
        0.76939621]])

12. Load the csv file into numpy array.

File:

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [81]:
a = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, None, None, 7, 8],
        [None, None, 9, 10, 11]
    ]
)

13. Subtract the mean of each row of a matrix.

In [83]:
r = np.random.rand(10, 10)
means = np.mean(r, axis=1)
r - means

array([[ 3.39493532e-01, -4.50471432e-02,  2.38149513e-02,
        -4.49083547e-01,  6.31480130e-02,  9.34675045e-02,
         4.44901700e-02, -5.40195725e-02, -1.22239620e-01,
        -3.92928373e-01],
       [-3.21403821e-01,  2.01843698e-01,  3.14197291e-01,
         1.31049451e-01, -1.21553680e-01,  3.73892363e-01,
         6.45648356e-01,  1.72179344e-01,  2.45513751e-01,
        -3.10000288e-01],
       [ 5.27537540e-01, -3.09556141e-01, -1.86814723e-01,
         4.66034881e-01, -6.76422965e-03,  4.16362857e-02,
         4.25379223e-01,  4.00316433e-01, -2.94879389e-01,
        -1.72671742e-01],
       [-2.29594145e-01, -5.17324472e-01,  3.83966613e-01,
        -4.34896430e-01,  3.28964390e-01, -2.86397585e-01,
         4.51027240e-01,  3.11272102e-01, -9.43411667e-02,
         1.87115950e-02],
       [-3.31582006e-01,  3.02756082e-01, -7.47625716e-02,
        -3.69366987e-01,  1.62816155e-02,  3.03739698e-01,
        -2.57749321e-01, -7.29735966e-02, -4.35406837e-01,
        -6.

14. Do a dot product of two matrices and print only the diagonal values.

In [86]:
r1 = np.random.rand(10, 10)
r2 = np.random.rand(10, 10)

dotted = np.dot(r1, r2)
diagonals = np.diag(dotted)
print(diagonals)

[1.47653066 2.24767198 1.30855363 2.72899967 1.37617103 2.50146881
 1.52873127 3.014201   1.40922402 2.19439176]


15. Swap two rows of a matrix.

In [89]:
r1 = np.random.rand(10, 10)
r2 = np.random.rand(10, 10)
print(r1[2,:], r2[2,:])
r1[2, :], r2[2, :] = r2[2, :], r1[2, :]
print(r1[2,:], r2[2,:])


[0.62841313 0.35431359 0.44402802 0.29327369 0.47342563 0.47750597
 0.44073947 0.89982877 0.34867607 0.35806907] [0.75171877 0.82496528 0.61473771 0.55093584 0.73772171 0.88774666
 0.42877372 0.13396249 0.81974128 0.79952507]
[0.75171877 0.82496528 0.61473771 0.55093584 0.73772171 0.88774666
 0.42877372 0.13396249 0.81974128 0.79952507] [0.75171877 0.82496528 0.61473771 0.55093584 0.73772171 0.88774666
 0.42877372 0.13396249 0.81974128 0.79952507]


16. Find a matrix rank.

In [90]:
r = np.random.rand(10, 10)
rank = np.linalg.matrix_rank(r)

17. Find the most frequent value in an array

In [97]:
r = np.random.randint(0, 10, (10, 10))
most_common = np.bincount(r.flatten()).argmax()
print(r)
print(most_common)

[[8 8 0 7 0 4 3 8 8 6]
 [2 5 0 9 0 5 0 2 4 5]
 [4 3 1 1 1 9 4 6 3 4]
 [6 9 2 8 9 1 5 7 6 9]
 [8 0 5 9 7 9 6 3 5 0]
 [6 0 7 8 1 4 3 4 6 0]
 [5 9 9 4 1 7 1 4 0 4]
 [0 9 9 9 6 1 9 4 9 4]
 [8 5 3 5 2 2 1 9 0 3]
 [9 9 5 4 9 3 3 4 5 0]]
9


18. Considering a four dimensions array, how to get sum over the last two axis at once?

In [100]:
r = np.random.rand(10, 10, 10, 10)
sums = r.sum(axis=(2, 3))
sums

array([[50.39236602, 46.24939342, 54.30341888, 48.64003689, 40.56122336,
        51.78741062, 48.31302872, 50.24868269, 44.13101418, 51.1694642 ],
       [50.43909949, 49.54737388, 51.78304773, 44.955803  , 50.64533024,
        51.94291792, 49.97022292, 48.80020236, 44.16666294, 45.68200076],
       [50.40783485, 50.08465879, 50.40026033, 51.01311253, 50.59843498,
        49.13372804, 48.69500462, 55.75829637, 45.2301391 , 48.01343883],
       [49.74110745, 55.54690458, 49.38073216, 52.4442085 , 51.66837969,
        49.33216181, 54.11588527, 52.1787646 , 49.20588552, 51.90773232],
       [49.27519683, 48.39612504, 51.0200606 , 53.07018488, 54.67183048,
        48.31092756, 49.02281132, 53.15745778, 51.18662442, 46.39369038],
       [48.15809338, 46.07249426, 54.58433626, 50.21287856, 50.02080772,
        50.02669955, 49.26839934, 51.05561325, 53.15590516, 51.88498132],
       [48.76667654, 52.34097914, 49.33376579, 52.59579208, 45.54100295,
        50.21286037, 50.00274486, 54.47967024